version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estoque-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vendas_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8082:8082"
    networks:
      - java_vendas-network

networks:
  java_vendas-network:
    external: true
